// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetapp.Dao;

#nullable disable

namespace aspnetapp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241031132137_V_0.1.0_重生")]
    partial class V_010_重生
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8");

            modelBuilder.Entity("aspnetapp.Models.AdminAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("T_AdminAccount");
                });

            modelBuilder.Entity("aspnetapp.Models.HomepageAd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Jumplink")
                        .HasColumnType("longtext");

                    b.Property<string>("PictureLink")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("T_HomepageAd");
                });

            modelBuilder.Entity("aspnetapp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualReturnTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ActualStartingTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Deposit")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DepositRefunded")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DispatchFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ExpectedReturnTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdentityCard")
                        .HasColumnType("longtext");

                    b.Property<bool>("LongTermLease")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("OtherFees")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Paid")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Rent")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TheRentalLocation")
                        .HasColumnType("int");

                    b.Property<int?>("TheReturnThePoint")
                        .HasColumnType("int");

                    b.Property<int?>("TheTransferPoint")
                        .HasColumnType("int");

                    b.Property<int>("TheUser")
                        .HasColumnType("int");

                    b.Property<int>("TheVehicle")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TheUser", "Status");

                    b.ToTable("T_OrderForm");
                });

            modelBuilder.Entity("aspnetapp.Models.RevenueStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("StoreA_Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("StoreB_Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TheOrder")
                        .HasColumnType("int");

                    b.Property<int>("TheStoreA")
                        .HasColumnType("int");

                    b.Property<int>("TheStoreB")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TheStoreA", "TheStoreB");

                    b.ToTable("T_RevenueStatistics");
                });

            modelBuilder.Entity("aspnetapp.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("BusinessHoursBegin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("BusinessHoursStart")
                        .HasColumnType("time(6)");

                    b.Property<bool>("BusinessStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("GpsLatitude")
                        .HasColumnType("double");

                    b.Property<double>("GpsLongitude")
                        .HasColumnType("double");

                    b.Property<string>("Introduce")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pictures")
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WeChat")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("T_StoreSummary");
                });

            modelBuilder.Entity("aspnetapp.Models.StoreAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TheStore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TheStore")
                        .IsUnique();

                    b.ToTable("T_StoreAccount");
                });

            modelBuilder.Entity("aspnetapp.Models.StoreMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Deposit")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Rent")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TheStore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TheStore");

                    b.ToTable("T_StoreMenu");
                });

            modelBuilder.Entity("aspnetapp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdentityCard")
                        .HasColumnType("longtext");

                    b.Property<string>("IdentityCardPictures")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nickname")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("T_Users");
                });

            modelBuilder.Entity("aspnetapp.Models.UserFavoritesStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TheStore")
                        .HasColumnType("int");

                    b.Property<int>("TheUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TheUser");

                    b.ToTable("T_UserFavoritesStore");
                });

            modelBuilder.Entity("aspnetapp.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("Certificate")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Drivinglicense")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FrameNumber")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Invoice")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCase")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Model")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .HasColumnType("longtext");

                    b.Property<string>("Pictures")
                        .HasColumnType("longtext");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PurchaseRegistrationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("StateUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TheCurrentStore")
                        .HasColumnType("int");

                    b.Property<int?>("TheOriginalStore")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VehicleIntroduction")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TheOriginalStore", "TheCurrentStore", "State");

                    b.ToTable("T_VehicleSummary");
                });

            modelBuilder.Entity("aspnetapp.Models.VehicleReplacementRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TheNewVehicles")
                        .HasColumnType("int");

                    b.Property<int>("TheOldVehicles")
                        .HasColumnType("int");

                    b.Property<int>("TheOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TheOrder");

                    b.ToTable("T_VehicleReplacementRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
