// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetapp.Dao;

#nullable disable

namespace aspnetapp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241010164115_v0.0.2_Store中的营业时间改为TimeSpan对应Mysql中的TIME类型")]
    partial class v002_Store中的营业时间改为TimeSpan对应Mysql中的TIME类型
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8");

            modelBuilder.Entity("aspnetapp.Models.HomepageAd", b =>
                {
                    b.Property<int>("AdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Jumplink")
                        .HasColumnType("longtext");

                    b.Property<string>("PictureLink")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AdId");

                    b.ToTable("T_HomepageAd");
                });

            modelBuilder.Entity("aspnetapp.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualReturnTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("DepositRefunded")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("DispatchFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ExpectedReturnTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LongTermLease")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("OtherFees")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Rent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RentalLocationStoreId")
                        .HasColumnType("int");

                    b.Property<int?>("ReturnThePointStoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TransferPointStoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("RentalLocationStoreId");

                    b.HasIndex("ReturnThePointStoreId");

                    b.HasIndex("TransferPointStoreId");

                    b.HasIndex("UserId");

                    b.ToTable("T_OrderForm");
                });

            modelBuilder.Entity("aspnetapp.Models.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("BusinessHoursBegin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("BusinessHoursStart")
                        .HasColumnType("time(6)");

                    b.Property<bool>("BusinessStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("GpsLatitude")
                        .HasColumnType("double");

                    b.Property<double>("GpsLongitude")
                        .HasColumnType("double");

                    b.Property<string>("Introduce")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pictures")
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WeChat")
                        .HasColumnType("longtext");

                    b.HasKey("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("T_StoreSummary");
                });

            modelBuilder.Entity("aspnetapp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdentityCard")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nickname")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("T_Users");
                });

            modelBuilder.Entity("aspnetapp.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("Certificate")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FrameNumber")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Invoice")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCase")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Model")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .HasColumnType("longtext");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PurchaseRegistrationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("StateUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VehicleIntroduction")
                        .HasColumnType("longtext");

                    b.HasKey("VehicleId");

                    b.HasIndex("StoreId");

                    b.ToTable("T_VehicleSummary");
                });

            modelBuilder.Entity("aspnetapp.Models.Order", b =>
                {
                    b.HasOne("aspnetapp.Models.Store", "RentalLocation")
                        .WithMany()
                        .HasForeignKey("RentalLocationStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aspnetapp.Models.Store", "ReturnThePoint")
                        .WithMany()
                        .HasForeignKey("ReturnThePointStoreId");

                    b.HasOne("aspnetapp.Models.Store", "TransferPoint")
                        .WithMany()
                        .HasForeignKey("TransferPointStoreId");

                    b.HasOne("aspnetapp.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalLocation");

                    b.Navigation("ReturnThePoint");

                    b.Navigation("TransferPoint");

                    b.Navigation("user");
                });

            modelBuilder.Entity("aspnetapp.Models.Store", b =>
                {
                    b.HasOne("aspnetapp.Models.User", null)
                        .WithMany("FavoriteStores")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("aspnetapp.Models.Vehicle", b =>
                {
                    b.HasOne("aspnetapp.Models.Store", "Store")
                        .WithMany("Vehicles")
                        .HasForeignKey("StoreId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("aspnetapp.Models.Store", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("aspnetapp.Models.User", b =>
                {
                    b.Navigation("FavoriteStores");
                });
#pragma warning restore 612, 618
        }
    }
}
