@localhost = https://localhost:63295
@id = 1
@phone = 13000000000
@password = 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b
@authorization = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwiZXhwIjoxNzMyNjk2ODAzfQ.Fk7FZ3cTCLJqw_cdAwg8qoJmg4ECPqnZUHJtghcsovI


### id 获取用户基础信息
GET {{localhost}}/user/id/{{id}} HTTP/1.1


### phone 获取用户基础信息
GET {{localhost}}/user/p/{{phone}} HTTP/1.1


### phone/password，登录
GET {{localhost}}/user/login/phone/{{phone}}/{{password}} HTTP/1.1


###
GET {{localhost}}/user/all/i HTTP/1.1
Authorization: Bearer {{authorization}}


### code，如未注册则创建用户，反之则返回用户基础信息
# POST {{localhost}}/user/ql/1 HTTP/1.1


### phone 获取用户收藏门店
#GET {{localhost}}/user/f/s/{{phone}} HTTP/1.1


### ======================== 门店 ===========================
### 获取所有门店信息
GET {{localhost}}/store/a HTTP/1.1


### ======================== 车辆 ===========================
### StoreId 获取门店所有车辆
GET {{localhost}}/vehicle/a/1 HTTP/1.1


### 
GET {{localhost}}/vehicle/1 HTTP/1.1


###
GET {{localhost}}/vehicle/model/1 HTTP/1.1


### ======================== 订单 ===========================
### StoreId 查询单个订单
GET {{localhost}}/order/i/{{id}} HTTP/1.1


### 
GET {{localhost}}/order/i/2 HTTP/1.1
Authorization: Bearer {{authorization}}


### 
GET {{localhost}}/order/i/a/0 HTTP/1.1
Authorization: Bearer {{authorization}}


### StoreId 查询订单
GET {{localhost}}/order/i/a/1 HTTP/1.1


### StoreId 添加单个订单
POST {{localhost}}/order/a HTTP/1.1
content-type: application/json

{
    "TheUser": 1,
    "UserName": "测试用户001",
    "UserPhone": "13666666666",
    "IdentityCard": "360000000000000000",
    "Vehicle": 1,
    "StartingTime": "2024-10-23",
    "ExpectedReturnTime": "2024-10-24",
    "RentalLocation": 1,
    "LongTermLease": false,
    "Deposit": 200,
    "Rent": 30,
    "Notes": "备注"
}