@localhost = https://localhost:63295
@id = 0
@phone = 13000000000
@password = 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b
@authorization = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwiZXhwIjoxNzM0MjUwOTcyfQ.5I0c8wFdnKcJqge1HqR_2V3pX_acIRyrawRsWBo37x4
@storeAccountauthorization = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJzdG9yZSIsImV4cCI6MTczMzA1NzQxMH0.Kaxj-TmORw6dIskJAfJAxVcSTk4cNYPNwzwJt-H-xrM



### id 获取用户基础信息
GET {{localhost}}/user/id/{{id}} HTTP/1.1


### phone 获取用户基础信息
GET {{localhost}}/user/p/{{phone}} HTTP/1.1


### phone/password，登录
GET {{localhost}}/user/login/phone/13000000000/{{password}} HTTP/1.1


###
GET {{localhost}}/user/all/i HTTP/1.1
Authorization: Bearer {{authorization}}



###
POST {{localhost}}/user/update/RealNameAuthentication HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{
    "Name": "ghmch",
    "IdentityCard": "360000000000000000"
}



### code，如未注册则创建用户，反之则返回用户基础信息
# POST {{localhost}}/user/ql/1 HTTP/1.1


### phone 获取用户收藏门店
#GET {{localhost}}/user/f/s/{{phone}} HTTP/1.1


### ======================== 门店 ===========================
### 获取所有门店信息
GET {{localhost}}/store/a HTTP/1.1


### ======================== 车辆 ===========================
### StoreId 获取门店所有车辆
GET {{localhost}}/vehicle/a/1 HTTP/1.1

### 
GET {{localhost}}/vehicle/1 HTTP/1.1


###
GET {{localhost}}/vehicle/model/1 HTTP/1.1


### ======================== 订单 ===========================
### 获取租车金额
GET {{localhost}}/order/calculate/1/2 HTTP/1.1


### 
GET {{localhost}}/order/a HTTP/1.1
Authorization: Bearer {{authorization}}


### Id 查询单个订单
GET {{localhost}}/order/i/19 HTTP/1.1
Authorization: Bearer {{authorization}}


### StoreId 添加单个订单
POST {{localhost}}/order/add HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{
    "StoreMenuId": 1,
    "DepositRequired": true,
    "UserName": "姓名",
    "UserPhone": "13000000000",
    "IdentityCard": "",
    "Vehicle": 1
}


###
POST {{localhost}}/order/pay/19 HTTP/1.1
Authorization: Bearer {{authorization}}

### ===================== 商家 =========================
### 登录
GET {{localhost}}/storeAccount/login/1/{{password}} HTTP/1.1


### 获取确认订单信息
GET {{localhost}}/storeAccount/confirm/order/13 HTTP/1.1
Authorization: Bearer {{storeAccountauthorization}}


### 确认订单
POST {{localhost}}/storeAccount/confirm HTTP/1.1
Authorization: Bearer {{storeAccountauthorization}}
content-type: application/json

{
    "OderId": 1,
    "TheVehicle": 1
}


### 确认还车
POST {{localhost}}/storeAccount/confirm/vehicle/return HTTP/1.1
Authorization: Bearer {{storeAccountauthorization}}
content-type: application/json

{
    "OderId": 28
}


### 下单 ==========================================================
Post {{localhost}}/order/pay HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{
    "orderId": 31
}


###
Post {{localhost}}/order/refund HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{
    "orderId": 34
}


###
POST {{localhost}}/order/callback/notify